spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: qcmicro-config-server-dev
---
spring:
  profiles: test
  application:
    name: qcmicro-config-server-dev 