spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8002
spring:
  profiles: dev
  application:
    name: qcmicro-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      test-while-idle: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: qcmicro-config-provider-dept-8002
    prefer-ip-address: true
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  type-aliases-package: com.qc.micro
  mapper-locations:
  - classpath:mybatis/mapper/**/*Mapper.xml
info:
  app.name: qcmicro-config-provider-dept-8002
  company.name: 青菜网络科技有限公司

---
server:
  port: 8102
spring:
  profiles: test
  application:
    name: qcmicro-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      test-while-idle: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: qcmicro-config-provider-dept-8102
    prefer-ip-address: true
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  type-aliases-package: com.qc.micro
  mapper-locations:
  - classpath:mybatis/mapper/**/*Mapper.xml
info:
  app.name: qcmicro-config-provider-dept-8102
  company.name: 青菜网络科技有限公司
