spring:
  profiles:
    active: 
    - dev
---
server:
  port: 1011
spring:
  application:
    profiles: dev
    name: qcmicro-config-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: qcmicro-config-zuul-1011
    prefer-ip-address: true
zuul:
#  prefix: /qc                                          
  ignored-services: "*"       #microservice-provider-dept       	# 忽略真实服务名
  routes:
    mydept.serviceId: qcmicro-config-provider-dept       			# 此配置将此服务名用下面的path代替
    mydept.path: /mydept/**
    myuser.userId: qcmicro-config-provider-user       				# 此配置将此服务名用下面的path代替
    myuser.path: /myuser/**

info:
  app.name: qcmicro-config-zuul-1011
  company.name: 青菜网络科技有限公司
---
server:
  port: 2011
spring:
  application:
    profiles: test
    name: qcmicro-config-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: qcmicro-config-zuul-2011
    prefer-ip-address: true
zuul:
#  prefix: /qc                                          
  ignored-services: "*"       #microservice-provider-dept        	# 忽略真实服务名
  routes:
    mydept.serviceId: qcmicro-config-provider-dept       			# 此配置将此服务名用下面的path代替
    mydept.path: /mydept/**
    myuser.userId: qcmicro-config-provider-user       				# 此配置将此服务名用下面的path代替
    myuser.path: /myuser/**
info:
  app.name: qcmicro-config-zuul-2011
  company.name: 青菜网络科技有限公司