spring:
  profiles:
    active:
    - dev
---
server:
  port: 7002
spring:
  profiles: dev    #开发环境
  application:
    name: qcmicro-config-eureka-7002
eureka:
  server:
    enable-self-preservation: true  #eureka自我保护机制（默认是true，无特殊要求建议使用默认）
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7012
spring:
  profiles: test    #测试环境
  application:
    name: qcmicro-config-eureka-7012
eureka:
  server:
    enable-self-preservation: true  #eureka自我保护机制（默认是true，无特殊要求建议使用默认）
  instance:
    hostname: eureka7012.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001.com:7011/eureka/